In [1]:
#Importo NumPy

In [2]:
import numpy as np

In [3]:
from numpy import mean, std

In [4]:
v = np.array([1,2,4,3,5])
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [5]:
#Visualizza size di v ed a

In [6]:
print("L'array v è composto da " + str(np.size(v)) + " elementi")

L'array v è composto da 5 elementi


In [7]:
print("L'array v è composto da " + str(np.size(a)) + " elementi")

L'array v è composto da 4 elementi


In [8]:
#Visualizza shape di v ed a

In [9]:
print(np.shape(v))

(5,)


In [10]:
print(np.shape(a))

(2, 2)


In [11]:
#Calcola il massimo, minimo, media e deviazione standard degli elementi di v

In [12]:
print("L'elemento massimo dell'array v è " + str(np.max(v)))

L'elemento massimo dell'array v è 5


In [13]:
print("L'elemento minimo dell'array v è " + str(np.min(v)))

L'elemento minimo dell'array v è 1


In [14]:
print("La media degli elementi dell'array v è " + str(np.mean(v)))

La media degli elementi dell'array v è 3.0


In [15]:
print("La deviazione standard degli elementi dell'array v è " + str(np.std(v)))

La deviazione standard degli elementi dell'array v è 1.4142135623730951


In [16]:
#Ordina gli elementi di v

In [17]:
print(np.sort(v))

[1 2 3 4 5]


In [18]:
#Calcola il risultato delle operazioni +, -, *, / e ** tra le matrici a e b

In [20]:
print(a+b)

[[ 6  8]
 [10 12]]


In [21]:
print(a-b)

[[-4 -4]
 [-4 -4]]


In [22]:
print(a*b)

[[ 5 12]
 [21 32]]


In [23]:
print(a/b)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [24]:
print(a**b)

[[    1    64]
 [ 2187 65536]]


In [25]:
#Crea un vettore con la sequenza 0-9.